sudo: required
services:
  - docker

before_install:
  - docker build -t namron/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true namron/react-test npm test

after_success:
  - docker build -t namron/multi-client ./client
  - docker build -t namron/multi-server ./server
  - docker build -t namron/multi-nginx ./nginx
  - docker build -t namron/multi-worker ./worker

  # Login to docker hub
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_ID}" --password-stdin

  # push images to docker hub
  - docker push namron/multi-client
  - docker push namron/multi-server
  - docker push namron/multi-nginx
  - docker push namron/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-central-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-eu-central-1-388051700118'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: ${AWS_ACCESS_KEY}
  secret_access_key: ${AWS_SECRET_KEY}
